spring:
  profiles:
    active: test



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?useSSL=false
    username: root
    password: phj161023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

